export default [
  {
    groupTitle: "그룹1",
    codes: [
      { title: "삼성전자", code: "005930" },
      { title: "네이버", code: "035420" },
      { title: "인탑스", code: "049070" },
      { title: "쏘카", code: "403550" },
      { title: "KODEX 유럽탄소배출권선물ICE(H)", code: "400570" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
    ],
    // color: "#ddd",
  },
  {
    groupTitle: "KB증권",
    codes: [
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
    ],
  },
  {
    groupTitle: "NH증권",
    codes: [
      { title: "KT&G", code: "033780" },
      { title: "LG전자", code: "066570" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
    ],
  },
  {
    groupTitle: "삼성증권",
    codes: [
      { title: "기아", code: "000270" },
      { title: "삼성전기", code: "009150" },
      { title: "LG유플러스", code: "032640" },
      { title: "TIGER KRX바이오K-뉴딜", code: "364970" },
      { title: "TIGER KRX2차전지K-뉴딜", code: "364980" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
    ],
  },
  {
    groupTitle: "신한증권",
    codes: [
      { title: "TIGER 미국다우존스30", code: "245340" },
      { title: "KODEX 선진국 MSCI World", code: "251350" },
      { title: "KODEX 종합채권(AA-이상)액티브", code: "273130" },
      { title: "KODEX 200미국채혼합", code: "284430" },
      { title: "KODEX 혁신기술테마액티브", code: "364690" },
      { title: "TIGER AI코리아프로스액티브", code: "365040" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
    ],
  },
  {
    groupTitle: "",
    codes: [
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
      { title: "", code: "" },
    ],
  },
]
